# Google Maven
# https://maven.google.com/web/index.html?hl=zh-cn

# Gradle Plugins
# https://plugins.gradle.org/

# Maven
# https://mvnrepository.com/

# Compose Compiler Maven
# https://androidx.dev/storage/compose-compiler/repository/

[versions]
agp = "8.10.0"
kotlin = "2.1.21"
compose = "1.8.2"
room = "2.7.1"
accompanist = "0.36.0"
rikka-shizuku = "13.1.5"
koin = "4.0.4"

[plugins]
agp-lib = { id = "com.android.library", version.ref = "agp" }
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# KSP quickstart
# https://kotlinlang.org/docs/ksp-quickstart.html
ksp = { id = "com.google.devtools.ksp", version = "2.1.21-2.0.1" }

[libraries]
androidx-annotation = { group = "androidx.annotation", name = "annotation", version = "1.9.1" }
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.16.0" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.9.0" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.10.1" }

compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version = "2.9.0" }
compose-materialIcons = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.7.8" }
material = { group = "com.google.android.material", name = "material", version = "1.12.0" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.3.2" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# Koin Inject
# https://insert-koin.io/docs/setup/koin
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

# Pager layouts
# https://google.github.io/accompanist/pager/
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist" }
accompanist-navigationAnimation = { group = "com.google.accompanist", name = "accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-flowlayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "accompanist" }
accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version = "0.37.3" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }

# AndroidHiddenApiBypass
# https://github.com/LSPosed/AndroidHiddenApiBypass
lsposed-hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version = "6.1" }

# Rikka Shizuku
# https://github.com/RikkaApps/Shizuku-API
rikka-shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "rikka-shizuku" }
rikka-shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "rikka-shizuku" }

# Dhizuku-API
# https://github.com/iamr0s/Dhizuku-API
iamr0s-dhizuku-api = { group = "io.github.iamr0s", name = "Dhizuku-SERVER_API", version = "0.0.5" }
