blank_issues_enabled: false
contact_links:
  - name: How do I activate Dhizuku
    url: https://github.com/iamr0s/Dhizuku/discussions/19
    about: For beginners
  - name: Cannot set device owner (Occured IllegalStateException)
    url: https://github.com/iamr0s/Dhizuku/discussions/19#already_accounts
    about: Not allowed to set the device owner because there are already some accounts on the device.
  - name: How to setup with QR code
    url: https://github.com/iamr0s/Dhizuku/discussions/118
    about: Android 7.0 or later
  - name: How to do if you cannot connect with Dhizuku v2.9
    url: https://github.com/iamr0s/Dhizuku/discussions/114
    about: For developers
